VERSION=1.1.5.2
PACKAGE=zcs-crm
MAINTAINER=Enrico Weigelt <enrico.weigelt@vnc.biz>
SECTION=free/zcs-office
PRIORITY=optional
DEPENDS=zcs-core-libs,zcs-lib-json-simple,zcs-lib-gson,zcs-lib-vnc-common,zcs-lib-vnc-pro
DESCRIPTION=Zimbra CRM
REDMINE_UPLOAD_PROJECT=zcs-crm
REDMINE_UPLOAD_URL=https://redmine.vnc.biz/redmine/
