VERSION=1.1.0.0
PACKAGE=zcs-crm
MAINTAINER=Enrico Weigelt <enrico.weigelt@vnc.biz>
SECTION=base
ARCHITECTURE=All
PRIORITY=optional
DEPENDS=zcs-core-libs,zcs-lib-json-simple,zcs-lib-gson,zcs-lib-vnc-common
DESCRIPTION=Zimbra CRM
REDMINE_UPLOAD_PROJECT=zcs-crm
REDMINE_UPLOAD_URL=https://redmine.vnc.biz/redmine/
