TOPDIR=../..

JSP_BUILD_JARS=\
	$(ZIMBRA_BUILD_ROOT)/lib/jars/zcs-lib-gson.jar		\
	$(ZIMBRA_BUILD_ROOT)/lib/jars/zcs-lib-json-simple.jar	\
	$(ZIMBRA_BUILD_ROOT)/lib/jars/zcs-lib-vnc-common.jar	\
	../lib_vnc_crm/ZimbraCRM.jar

include $(TOPDIR)/zcs-core-jsp.mk
