
TOPDIR=../../
JAR_FILE_NAME=ZimbraCRM.jar

## list jar files which need to be added to classpath
## (taken from $ZIMBRA_ROOT/lib/jars)
ZCS_LIB_JARS=\
	zimbracommon.jar	\
	zimbrastore.jar		\
	zcs-lib-json-simple.jar	\
	zcs-lib-gson.jar

INSTALL_ZIMLET=y
INSTALL_USER=y
INSTALL_ADMIN=y
INSTALL_SERVICE=y
INSTALL_EXTENSION=y

include $(TOPDIR)/zcs-java-lib.mk
