ZIMLET_NAME=biz_vnc_crm_admin
TOPDIR=../..

JSP_BUILD_JARS=\
    $(ZIMBRA_BUILD_ROOT)/lib/jars/zcs-lib-gson.jar      \
    $(ZIMBRA_BUILD_ROOT)/lib/jars/zcs-lib-json-simple.jar   \
    ../lib_vnc_crm/ZimbraCRM.jar\
    $(ZIMBRA_BUILD_ROOT)/lib/jars/zcs-lib-vnc-common.jar    \
    $(ZIMBRA_BUILD_ROOT)/lib/jars/zcs-lib-vnc-pro.jar   \
    $(ZIMBRA_BUILD_ROOT)/lib/jars/zimbrastore.jar   \
    $(ZIMBRA_BUILD_ROOT)/lib/jars/zimbracommon.jar

include $(TOPDIR)/common.mk
include $(ZIMBRA_BUILD_ROOT)/extensions-extra/zmpkg/mk/zcs-zimlet.mk
