ZIMLET_NAME=biz_vnc_crm_client
TOPDIR=../..

JSP_BUILD_JARS=\
	$(ZIMBRA_BUILD_ROOT)/lib/jars/zcs-lib-gson.jar		\
	$(ZIMBRA_BUILD_ROOT)/lib/jars/zcs-lib-json-simple.jar	\
	../lib_vnc_crm/ZimbraCRM.jar\
	$(ZIMBRA_BUILD_ROOT)/lib/jars/zcs-lib-vnc-common.jar

include $(TOPDIR)/zcs-zimlet.mk
